# Generated by Django 5.1.7 on 2025-03-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
