# Generated by Django 5.1.7 on 2025-03-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_alter_cv_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='user',
            new_name='cv',
        ),
    ]
