# Generated by Django 5.1.7 on 2025-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_rename_user_block_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.CharField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
