# Generated by Django 5.1.7 on 2025-03-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_alter_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
