# Generated by Django 5.1.7 on 2025-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0007_alter_cv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.CharField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
