# Generated by Django 5.1.7 on 2025-03-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0010_alter_block_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('startAt', models.DateTimeField()),
                ('endAt', models.DateTimeField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='CV.block')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'ordering': ['title'],
            },
        ),
    ]
