# Generated by Django 5.1.7 on 2025-03-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0011_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='endAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='startAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
