# Generated by Django 5.1.7 on 2025-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0013_alter_line_endat_alter_line_startat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='endAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='startAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
