# Generated by Django 5.1.7 on 2025-03-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('zipCode', models.CharField(default='', max_length=10)),
                ('country', models.CharField(default='France', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.adress'),
        ),
    ]
